### PR TITLE
moved events calendar button text to en locale

### PR DESCRIPTION
**Pull request by eddiewebb**
Moves hard coded button text to translation files.

### CODE REVIEW

**Comment by eddiewebb** [comment]
@LCinHK - any chance you could add this to your contributed translations?

**Comment by LCinHK** [comment]
Gotcha.
Done, where should I put the yml files? Open a new pull request

**Comment by LCinHK** [comment]
#### zh.yml, zh-hans.yml, cn.yml↓
```
flarum-calendar:
  forum:
    button:
      landing: 事件日历
      create: "新事件"
      login: "添加你的事件"
    modal:
      submit: "提交"

  admin:
    permissions:
      add: 创建新的日历事件
      moderate: 移除或编辑日历事件 (所有用户都可编辑他们自己创建的)
    basics:
      homepage: 本日历月
```
#### zh-hant.yml
```
flarum-calendar:
  forum:
    button:
      landing: 事件日曆
      create: "新事件"
      login: "添加你的事件"
    modal:
      submit: "提交"

  admin:
    permissions:
      add: 創建新的日曆事件
      moderate: 移除或編輯日曆事件 (所有用戶都可編輯他們自己創建的)
    basics:
      homepage: 本日曆月
```

#### ja.yml
```
flarum-calendar:
  forum:
    button:
      landing: イベントカレンダー
      create: "新イベント"
      login: "あなたの新イベントを追加"
    modal:
      submit: "確認"

  admin:
    permissions:
      add: カレンダーに新イベントを追加する
      moderate: カレンダーに新イベントを削除、編集する (誰でも自分のイベントを編集できます)
    basics:
      homepage: カレンダー・今月
```

**Comment by eddiewebb** [comment]
thank you @LCinHK !!!!  I added them to the appropriate files.

**Pull request merged**
